// ============================================================
// 📝 Doc Templates — Zero-token documentation generation
// Each template uses {{placeholder}} variables for dynamic data.
// ============================================================

export const TEMPLATES = {
  header: "# 📋 System Documentation\n\n> **Auto-generated by System Agent DocGenerator**\n> {{date}} at {{time}} | Commit: `{{commit}}`\n\n---\n\n",

  changelog: "## 🔄 Changelog\n\n{{content}}\n",

  api: "## 🌐 API Routes\n\n{{content}}\n",

  tools: "## 🛠️ Tools Registry\n\n{{content}}\n",

  agents: "## 🤖 Agents\n\n{{content}}\n",

  architecture: "## 🏗️ System Architecture\n\n{{content}}\n",

  packages: "## 📦 Package Structure\n\n{{content}}\n",

  footer: "---\n\n*Documentation generated by [System Agent DocGenerator](http://localhost:54520)*\n",

  changelogSection: "### Commits\n```\n{{commits}}\n```\n\n### Changed Files\n| File | Type |\n|------|------|\n{{filesTable}}\n\n{{stat}}\n",

  apiSection: "**{{packageName}}**\n\n| Method | Path | Description |\n|--------|------|-------------|\n{{routesTable}}\n",

  toolsSection: "Total: **{{total}} tools**\n\n| Tool Name | Description |\n|-----------|-------------|\n{{toolsTable}}\n",

  agentsSection: "Mode: **{{mode}}** | Max Concurrent: **{{maxConcurrent}}**\n\n| Agent | Role | Status | Tasks |\n|-------|------|--------|-------|\n{{agentsTable}}\n",

  architectureSection: "### Services ({{total}} total)\n\n| Service |\n|---------|\n{{servicesTable}}\n",

  packagesSection: "| Package | Description |\n|---------|-------------|\n{{packagesTable}}\n",
};

export type DocType = "changelog" | "api" | "tools" | "agents" | "architecture" | "packages" | "all";

export const DOC_TYPES: DocType[] = [
  "changelog", "api", "tools", "agents", "architecture", "packages",
];

export const DOC_LABELS: Record<DocType, string> = {
  changelog: "Changelog",
  api: "API Routes",
  tools: "Tools Registry",
  agents: "Agents",
  architecture: "System Architecture",
  packages: "Package Structure",
  all: "All",
};
