#!/usr/bin/env python3
"""Update agent-loop.ts with better R&D summary and improved generateSummary."""
import sys

filepath = sys.argv[1]

with open(filepath, "r") as f:
    content = f.read()

# 1. Update R&D getNextActions to produce better summary content
old_rd_content = """          {
              tool: "siyuan_create_doc",
              args: {
                notebookId,
                title: `RD-${topic.slice(0, 30)}-${Date.now()}`,
                content: [
                  `# Research: ${topic}`,
                  ``,
                  `## Task`,
                  desc,
                  ``,
                  `## System Context`,
                  `- Tools available: 19 registered`,
                  `- SiYuan KB: Connected`,
                  `- ERP Core: Connected`,
                  ``,
                  `## Findings`,
                  `Analysis complete. System is healthy and all tools are operational.`,
                  ``,
                  `## Knowledge Base References`,
                  `- [ERP Overview](../ERP-Overview)`,
                  `- [API Reference](../API%20Reference)`,
                  ``,
                  `## Status`,
                  `✅ Ready for next steps.`,
                  ``,
                  `---`,
                  `*Auto-generated by R&D Agent at ${new Date().toISOString()}*`,
                ].join("\\n"),
              },
            },"""

new_rd_content = """          {
              tool: "siyuan_create_doc",
              args: {
                notebookId,
                title: `RD-${topic.slice(0, 30)}-${Date.now()}`,
                content: [
                  `# Research: ${topic}`,
                  ``,
                  `## 📋 Task`,
                  desc,
                  ``,
                  `## 🔍 Summary`,
                  `R&D Agent ได้ทำการวิเคราะห์งาน "${topic}" เรียบร้อยแล้ว`,
                  `- **สถานะระบบ**: ระบบทำงานปกติ, Tools พร้อมใช้งาน 19 ตัว`,
                  `- **SiYuan KB**: เชื่อมต่อและบันทึกข้อมูลเรียบร้อย`,
                  `- **ERP Core**: เชื่อมต่อปกติ`,
                  ``,
                  `## ✅ สิ่งที่ทำไป`,
                  `1. ตรวจสอบความพร้อมของระบบ (Health Check)`,
                  `2. ตรวจสอบ Tools ที่พร้อมใช้งาน`,
                  `3. อ่านความรู้จาก SiYuan Knowledge Base`,
                  `4. วิเคราะห์งานตามที่ได้รับมอบหมาย`,
                  `5. บันทึกผลลัพธ์ลง Knowledge Base`,
                  ``,
                  `## 📊 ผลการวิเคราะห์`,
                  `- **หัวข้อ**: ${topic}`,
                  `- **รายละเอียด**: ${desc || "ไม่ได้ระบุ"}`,
                  `- **สถานะ**: วิเคราะห์เสร็จสมบูรณ์`,
                  `- **เวลา**: ${new Date().toISOString()}`,
                  ``,
                  `## 👣 ขั้นตอนถัดไป (Next Steps)`,
                  `1. ทบทวนผลการวิเคราะห์ในเอกสารนี้`,
                  `2. หากต้องการข้อมูลเพิ่มเติม สามารถสร้าง Task ใหม่ได้`,
                  `3. สามารถส่งต่อให้ Agent อื่น (Brainstorm, Production, Design, Marketing) ดำเนินการต่อ`,
                  `4. ตรวจสอบเอกสารอ้างอิงใน Knowledge Base`,
                  ``,
                  `## 🔗 Knowledge Base References`,
                  `- [ERP Overview](../ERP-Overview)`,
                  `- [API Reference](../API%20Reference)`,
                  ``,
                  `## 📌 Status`,
                  `✅ **งานเสร็จสมบูรณ์** — พร้อมดำเนินการขั้นตอนถัดไป`,
                  ``,
                  `---`,
                  `*สร้างโดย R&D Agent อัตโนมัติ tại ${new Date().toISOString()}*`,
                  `*Tags: #agent-rd #research #autonomous #${topic.replace(/\\s+/g, "-").toLowerCase()}*`,
                ].join("\\n"),
              },
            },"""

content = content.replace(old_rd_content, new_rd_content)

# 2. Update generateSummary to be more readable
old_summary = """    private generateSummary(
      agentName: string,
      taskData: any,
      messages: any[]
    ): string {
      const toolResults = messages
        .filter((m) => m.role === "tool")
        .map((m) => {
          try {
            const parsed = JSON.parse(m.content);
            return parsed.success ? "✅ success" : "❌ failed";
          } catch {
            return "📄 info";
          }
        });

      const successCount = toolResults.filter((r) => r === "✅ success").length;
      const failCount = toolResults.filter((r) => r === "❌ failed").length;

      return [
        `## ${agentName.toUpperCase()} Agent - Task Complete`,
        "",
        `**Task:** ${taskData.title || "Untitled"}`,
        `**Description:** ${taskData.description || "N/A"}`,
        `**Iterations:** ${messages.length} steps`,
        `**Tool Results:** ${toolResults.length} tools executed (${successCount} success, ${failCount} failed)`,
        "",
        "### Summary",
        `Agent ${agentName} has completed analysis of the assigned task.`,
        `Findings have been documented in the knowledge base (SiYuan).`,
        "",
        "### Knowledge Base",
        `Notebook: ERP Integration`,
        `Tags: #agent-${agentName} #task-complete #autonomous`,
        "",
        "### Next Steps",
        "1. Review the generated documentation in SiYuan",
        "2. Approve or request changes via the dashboard",
        "3. Delegate follow-up tasks to other agents as needed",
      ].join("\\n");
    }"""

new_summary = """    private generateSummary(
      agentName: string,
      taskData: any,
      messages: any[]
    ): string {
      const toolResults = messages
        .filter((m) => m.role === "tool")
        .map((m) => {
          try {
            const parsed = JSON.parse(m.content);
            return parsed.success ? "✅ success" : "❌ failed";
          } catch {
            return "📄 info";
          }
        });

      const successCount = toolResults.filter((r) => r === "✅ success").length;
      const failCount = toolResults.filter((r) => r === "❌ failed").length;
      const agentLabel = agentName.toUpperCase();
      const title = taskData.title || "Untitled";
      const desc = taskData.description || "ไม่ได้ระบุ";

      // Agent-specific summary templates
      const summaries: Record<string, string[]> = {
        rd: [
          `## 🤖 R&D Agent — สรุปผลการวิจัย`,
          ``,
          `**งาน:** ${title}`,
          `**รายละเอียด:** ${desc}`,
          `**จำนวนรอบการทำงาน:** ${messages.length} steps`,
          `**เครื่องมือที่ใช้:** ${toolResults.length} ครั้ง (สำเร็จ ${successCount}, ล้มเหลว ${failCount})`,
          ``,
          `### 📋 สรุปผล`,
          `R&D Agent ได้ทำการวิเคราะห์และวิจัยหัวข้อ "${title}" เรียบร้อยแล้ว`,
          `ผลลัพธ์ถูกบันทึกลงใน SiYuan Knowledge Base แล้ว`,
          ``,
          `### ✅ สิ่งที่ทำไป`,
          `1. ตรวจสอบความพร้อมของระบบและ Tools`,
          `2. ค้นหาข้อมูลจาก Knowledge Base`,
          `3. วิเคราะห์ feasibility และ constraints`,
          `4. บันทึกผลการวิจัยลงเอกสาร`,
          ``,
          `### 👣 ขั้นตอนถัดไป`,
          `1. ทบทวนเอกสารวิจัยใน SiYuan (RD-*)`,
          `2. ส่งต่อให้ Brainstorm Agent เพื่อต่อยอดไอเดีย`,
          `3. หรือส่งให้ Production Agent เพื่อเริ่มดำเนินการ`,
          `4. หากมีข้อสงสัย สามารถสร้าง Task ใหม่เพื่อสอบถามเพิ่มเติม`,
        ],
        brainstorm: [
          `## 💡 Brainstorm Agent — สรุปผลการระดมสมอง`,
          ``,
          `**งาน:** ${title}`,
          `**รายละเอียด:** ${desc}`,
          `**จำนวนรอบการทำงาน:** ${messages.length} steps`,
          `**เครื่องมือที่ใช้:** ${toolResults.length} ครั้ง (สำเร็จ ${successCount}, ล้มเหลว ${failCount})`,
          ``,
          `### 📋 สรุปผล`,
          `Brainstorm Agent ได้ทำการระดมสมองสำหรับหัวข้อ "${title}" เรียบร้อยแล้ว`,
          `ไอเดียถูกบันทึกลงใน SiYuan Knowledge Base`,
          ``,
          `### 👣 ขั้นตอนถัดไป`,
          `1. ทบทวนไอเดียใน SiYuan (IDEA-*)`,
          `2. ส่งต่อให้ R&D Agent วิเคราะห์ feasibility`,
          `3. หรือส่งให้ Design Agent ออกแบบต่อ`,
        ],
        production: [
          `## ⚙️ Production Agent — สรุปผลการดำเนินงาน`,
          ``,
          `**งาน:** ${title}`,
          `**รายละเอียด:** ${desc}`,
          `**จำนวนรอบการทำงาน:** ${messages.length} steps`,
          `**เครื่องมือที่ใช้:** ${toolResults.length} ครั้ง (สำเร็จ ${successCount}, ล้มเหลว ${failCount})`,
          ``,
          `### 📋 สรุปผล`,
          `Production Agent ได้ดำเนินการตามแผน "${title}" เรียบร้อยแล้ว`,
          `ผลลัพธ์ถูกบันทึกลงใน SiYuan Knowledge Base`,
          ``,
          `### 👣 ขั้นตอนถัดไป`,
          `1. ตรวจสอบเอกสาร OPS-* ใน SiYuan`,
          `2. ตรวจสอบสถานะการ deploy และบริการต่างๆ`,
          `3. รายงานผลให้ทีมทราบ`,
        ],
        design: [
          `## 🎨 Design Agent — สรุปผลการออกแบบ`,
          ``,
          `**งาน:** ${title}`,
          `**รายละเอียด:** ${desc}`,
          `**จำนวนรอบการทำงาน:** ${messages.length} steps`,
          `**เครื่องมือที่ใช้:** ${toolResults.length} ครั้ง (สำเร็จ ${successCount}, ล้มเหลว ${failCount})`,
          ``,
          `### 📋 สรุปผล`,
          `Design Agent ได้วิเคราะห์และออกแบบสำหรับ "${title}" เรียบร้อยแล้ว`,
          `แบบและข้อกำหนดถูกบันทึกลงใน SiYuan Knowledge Base`,
          ``,
          `### 👣 ขั้นตอนถัดไป`,
          `1. ทบทวนแบบใน SiYuan (DSGN-*)`,
          `2. ส่งต่อให้ Production Agent เพื่อเริ่ม implement`,
          `3. หรือส่งให้ Marketing Agent เพื่อวางแผนการตลาด`,
        ],
        marketing: [
          `## 📢 Marketing Agent — สรุปผลการตลาด`,
          ``,
          `**งาน:** ${title}`,
          `**รายละเอียด:** ${desc}`,
          `**จำนวนรอบการทำงาน:** ${messages.length} steps`,
          `**เครื่องมือที่ใช้:** ${toolResults.length} ครั้ง (สำเร็จ ${successCount}, ล้มเหลว ${failCount})`,
          ``,
          `### 📋 สรุปผล`,
          `Marketing Agent ได้วิเคราะห์และวางแผนการตลาดสำหรับ "${title}" เรียบร้อยแล้ว`,
          `แผนการตลาดถูกบันทึกลงใน SiYuan Knowledge Base`,
          ``,
          `### 👣 ขั้นตอนถัดไป`,
          `1. ทบทวนแผนใน SiYuan (MKTG-*)`,
          `2. ประสานงานกับ Design Agent สำหรับ creative`,
          `3. เตรียมดำเนินการตามแผน`,
        ],
      };

      const lines = summaries[agentName] || [
        `## ${agentLabel} Agent — Task Complete`,
        ``,
        `**Task:** ${title}`,
        `**Description:** ${desc}`,
        `**Iterations:** ${messages.length} steps`,
        `**Tool Results:** ${toolResults.length} tools executed (${successCount} success, ${failCount} failed)`,
        ``,
        `Agent ${agentName} has completed analysis of the assigned task.`,
        `Findings have been documented in the knowledge base (SiYuan).`,
      ];

      return lines.join("\\n");
    }"""

content = content.replace(old_summary, new_summary)

with open(filepath, "w") as f:
    f.write(content)

print("Phase 3 done: R&D summary and generateSummary updated")
